spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ''
        url: jdbc:postgresql://localhost:5432/books
        username: ''
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
    profiles:
        active: spring.profiles.active

